### PR TITLE
Added pytorch docker setup and changed the main.py to othello(8) game

### PR DESCRIPTION
**Pull request by marcoleewow**
I added docker setup for reproducible python environment. Also note that I changed README.md to add some notes for docker installation and changed `main.py` to othello(8) game.

### CODE REVIEW

**Comment by suragnair** [comment]
Hi, thanks for the Dockerfile and PyTorch 0.4 migration. Some suggestions- it would be great if you can move the Dockerfile and related files into `docker/pytorch/` so that we can have separate ones for other frameworks as well. Also it would be best to leave `main.py` and `pit.py` for 6x6 as that's fine for the default.

Thanks again!

**Comment by marcoleewow** [comment]
Since there will be some shared files between different frameworks like `jupyter_notebook_config.py` and `run_jupyter.sh`, I planned to name the dockerfiles to be `Dockerfile.pytorch` and `Dockerfile.tensorflow` instead so that they share the same folder for easier docker build. I will add dockerfiles for keras + tensorflow later when I have time. Do you think its reasonable or shall I still move them to different docker folder?

**Comment by suragnair** [comment]
Hmm yeah, that's reasonable. Can you default to 6x6 though?

**Comment by marcoleewow** [comment]
Yes sure, I will do that this weekend!

**Comment by suragnair** [comment]
@marcoleewow any updates?

**Pull request merged**
