### PR TITLE
Dots and Boxes implementation for AlphaZero

### PR DESCRIPTION
**Pull request by carlos-aguayo**
Trained version for Dots and Boxes game

JavaScript implementation in
https://github.com/carlos-aguayo/carlos-aguayo.github.io/tree/master/alphazero

Web version here:
https://carlos-aguayo.github.io/alphazero/

### CODE REVIEW

**Comment by carlos-aguayo** [comment]
@suragnair Hi, here are game rules and a trained version for the Dots and Boxes game. I ported it to JavaScript and made a simple webapp. I'll be posting soon a blog post in Medium and would like to reference your repo. 
Great work!
Let me know if you have any feedback about these changes.

**Comment by suragnair** [comment]
Hi Carlos, thanks for the contribution. The webapp is slick! Was able to play a few games, but occasionally it got stuck in the beginning when AI was player 2.

Excited to see the blog post. How about after you write the post, you can add the link to the webapp and the blog to the README and then I can merge?

**Comment by carlos-aguayo** [comment]
Thanks @suragnair ! I've fixed the issue that you found. 

Here's a draft for the blog post, in case that you would like to provide feedback.

Once the blog post gets published, I'll do as you said and add the link to the webapp and the blog to the README.

**Comment by carlos-aguayo** [comment]
The [blog post](https://towardsdatascience.com/alphazero-a-novel-reinforcement-learning-algorithm-deployed-in-javascript-56018503ad18) has gone live! In it I have a few links that still link to my fork. If this can get merged, I'll make sure I update those links to your fork.
Thanks and great work! Your implementation of AlphaZero was so simple and educational!

[](https://towardsdatascience.com/alphazero-a-novel-reinforcement-learning-algorithm-deployed-in-javascript-56018503ad18)

**Comment by suragnair** [comment]
Thank you! Ready to push once you add the links. Everything looks great!

**Comment by carlos-aguayo** [comment]
@suragnair I just updated the links. It's a bit hard to see in the diff, you can see new state here: https://github.com/carlos-aguayo/alpha-zero-general/tree/dotsandboxes/dotsandboxes

Thanks again! Your code is great!

**Pull request merged**
