### PR TITLE
Use tqdm() library and remove pytorch_classification Bar

### PR DESCRIPTION
**Pull request by mikhail**
I removed individual game-specific dependencies as well, though I'd really love to see all these copy-paste files go away and have one top-level file that is configurable (either via main.py file or better yet - some config file inside of game directories!)

This addresses the tqdm bit of #180

### CODE REVIEW

**Comment by suragnair** [comment]
There seem to be some conflicts after merging the logging PR. Also, previously the training steps would print the running `loss_pi` and `loss_v`. Would it be possible to incorporate those in the tqdm bars?

**Comment by mikhail** [comment]
Yep! I'll resolve the conflicts and add those values back as a suffix to tqdm

**Comment by mikhail** [comment]
Updated! Looks like this now: 
image

**Comment by suragnair** [comment]
This is awesome! It cleans up a lot of bookkeeping code and hopefully makes the code easier to use. Thanks very much. Would be open to other suggestions for overall repo hygiene.

**Pull request merged**
