### PR TITLE
Add 3D TicTacToe

### PR DESCRIPTION
**Pull request by goshawk22**
Adds 3D TicTacToe.
Also adds pretrained model (although not trained for very long).
Not sure that all the code is very clean/well coded so might need checking (seems to work though).

### CODE REVIEW

**Comment by suragnair** [comment]
Thanks so much for the contribution! Can you also add it to https://github.com/suragnair/alpha-zero-general/blob/master/test_all_games.py and make sure the tests run?

**Comment by suragnair** [comment]
And also edit the main README to add your name/github handle to the list of contributors!

**Comment by goshawk22** [comment]
I won't be able to do it until next week but will do it then. Thank you.

**Comment by goshawk22** [comment]
I won't be able to do it until next week, but I will do it then. Thank you.

**Comment by suragnair** [comment]
#156 This bug fix may have some repercussions for tic-tac-toe like games and may significantly enhance performance. Please have a look!

**Comment by goshawk22** [comment]
I will. This is very helpful!

**Comment by goshawk22** [comment]
All done now.
For some reason the model is unbeatable when it goes first, but plays almost the opposite when the human player goes first. Not sure what's wrong here. I adjusted the code as in the recent error #156 
Any ideas?
TODO: Add support for 4x4x4

**Comment by goshawk22** [comment]
It's as if the model is assuming that, because the 3x3x3 game is solved, you will win whatever it does, and doesn't bother to play.

**Comment by goshawk22** [comment]
I will try the 4x4x4 soon and see if it is a problem with the code, or because the game is solved.

**Comment by goshawk22** [comment]
It seems that connect 4 and TicTacToe are also solved. Could this also effect the performance of the model when playing second?

**Comment by HaraldKorneliussen** [comment]
This is a problem you run into with traditional alpha-beta tree search also. 

One way to solve it is to value a late loss slightly more than an early loss.

**Comment by goshawk22** [comment]
OK, I'm not sure how this could be implemented. Any idea?

**Comment by goshawk22** [comment]
OK added support for 4x4x4 Game

**Comment by goshawk22** [comment]
Ready to merge now

**Pull request closed without merging**
