### PR TITLE
Connect4 pitting

### PR DESCRIPTION
**Pull request by NMO13**
Implementation of pitting for Connect4 (CPU/Human or CPU/CPU).
Unfortunately, I cannot provide a pretrained model since the model size is already over 120MB. Github only allows file sizes of maximum 100MB.

### CODE REVIEW

**Comment by mikhail** [comment]
What is different about this file than the top-level pit file? Is there a way to make the top level file more configurable to keep it DRY?

**Comment by NMO13** [comment]
That would be the cleanest solution but we have to integrate the other pitting files (rts, tafl, ...) as well. Since I don't know these games and their requirements, I sticked to the current policy of creating a separate pit file for every game.

**Comment by NMO13** [comment]
Based on your criticism regarding DRYness, I have extracted the core pitting logic into a separate file. 
Review welcome.

**Comment by mikhail** [comment]
This is definitely more DRY. I personally would've implemented it differently - keeping top level pit file as the main executable and generic, and have settings done per game. It would also help avoid the weirdness with changing system path inside the script. @suragnair thoughts?

**Comment by NMO13** [comment]
I forgot to extract ```numMCTSSims': 50, 'cpuct': 1.0```.  I will fix that.

**Comment by suragnair** [comment]
I would also prefer having the top level pit file as the main executable if possible, but I do agree it has gotten clunky.

**Comment by NMO13** [comment]
I changed it now so that the top level file it the main file. Settings can now be done per game by overriding a create method in a builder class.

> It would also help avoid the weirdness with changing system path inside the script.
Changing system paths in the code is not necessary anymore.

**Comment by mikhail** [comment]
Nice! yeah I like this a lot. Feel free to copy/paste my stuff from #185 , or if @suragnair wants -- merge this and I'll piggyback off of this after it's merged.

**Comment by NMO13** [comment]
I wait for @suragnair  's opinion. If he likes this approach as well then I will adapt the pitting files of the other games as well and integrate your  #185

**Comment by suragnair** [comment]
Yep this + #185 looks great! Should we make a dev branch for incorporating these?

**Comment by NMO13** [comment]
Yes sounds like a good idea.

**Comment by NMO13** [comment]
So you will create a dev branch right? Bc I have no permission. :-)

**Comment by suragnair** [comment]
It's there

**Comment by NMO13** [comment]
Great, I take care of the integration.

**Comment by NMO13** [comment]
I finally managed to find time to implement the changes as promised.

**Pull request closed without merging**
