### PR TITLE
Add 3D TicTacToe

### PR DESCRIPTION
**Pull request by goshawk22**
Added 3D TicTacToe, both 3x3x3 and 4x4x4.

### CODE REVIEW

**Comment by suragnair** [comment]
Thanks very much!

**Comment by ilyakz** [comment]
https://github.com/ilyakz/alpha-game2
Perhaps you will find something for yourself here. The old version of the framework was already used. But the added pygame elements and the game supports any square dimension. 
Models were also created in pytorch and tensorflow, but I did not upload them due to the lack of an opportunity to check the models. If necessary, I can search in my old files and add.

**Comment by goshawk22** [comment]
This implementation works and has been able to solve the game in a 3x3x3 board, so I think it is working quite well!

**Comment by ilyakz** [comment]
The game 3 * 3 * 3 is mathematically useless, since the chance to win is always greater with the one who started the game first.

**Comment by goshawk22** [comment]
The game is solved - whoever starts first will win if they play optimally.
That is why I also implemented a 4*4*4 version of the game.

**Comment by ilyakz** [comment]
I understand. I have nothing against your version. I just added my old version, implemented a little differently and with a graphical interface. Suddenly someone will see and it will be useful for him too.))

**Comment by goshawk22** [comment]
Ah OK I understand now - I'll take a look at your GUI, it will be interesting to see how you've done it!
Thank you for showing me!

**Pull request merged**
